#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#Make run file executeable
# Change ownership of /app
echo "chown /app"
lsiown -R abc:abc /app

# Change ownership of /config
echo "chown /config"
lsiown -R abc:abc /config

# Change ownership of /databases
echo "chown /databases"
lsiown -R abc:abc /databases

# Start the PowerShell script with tini
echo "start discord-bot main script"
s6-setuidgid abc /usr/bin/tini -s -- python /app/bot.py --
