#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Change ownership of /app
echo "chown /app"
chown -R abc:abc /app

# Change ownership of /config
echo "chown /config"
chown -R abc:abc /config

# Change ownership of /databases
echo "chown /databases"
chown -R abc:abc /databases

# Activate the virtual environment
echo "Activate virtual environment"
source /venv/bin/activate

# Start the Discord bot
echo "Start discord-bot main script"
s6-setuidgid abc python /app/bot.py
