name: Build Docker Image
on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - ".github/**"
      - "LICENSE"
      - "**.md"

jobs:
  GHRC:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: FranzDiebold/github-env-vars-action@v2.8.0
      - name: Print environment variables
        run: |
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
          echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"

      - name: Prepare GHRC.io
        id: prep
        run: |
          REPO=$CI_REPOSITORY_NAME
          DOCKER_IMAGE=${{ github.repository_owner }}/${REPO}
          if [[ "$CI_REF_NAME" == "main" ]]; then
            VERSION=latest
          else
            VERSION=$CI_REF_NAME
          fi
          RUNNERNR=$CI_RUN_NUMBER
          CREATED=$(date +'%Y-%m-%dT%H:%M:%SZ')
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=title::${GITHUB_REPOSITORY}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=created::${CREATED}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.11.0

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES }}

      - name: Build and push GHRC.io
        id: docker_build
        uses: docker/build-push-action@v6.12.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: |
            ghcr.io/${{ steps.prep.outputs.tags }}
          build-args: |
            COMMIT_TAG=${{ github.sha }}  # Pass the commit hash as COMMIT_TAG
          labels: |
            org.opencontainers.image.title=${{ steps.prep.outputs.title }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Send Enhanced Discord Notification
        if: success()
        run: |
          # Get short SHA - fix the variable capture
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          # Create commit link properly formatted for the Discord notification
          COMMIT_LINK="\`${SHORT_SHA}\`"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          # Determine branch and tags info - we need to use string values for colors
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            BRANCH="main"
            BRANCH_COLOR="4885929"  # Decimal for Green
            IMAGE_TAGS="${{ env.RELEASE_VERSION }}, latest"
          elif [[ "$GITHUB_REF" == refs/heads/dev ]]; then
            BRANCH="dev"
            BRANCH_COLOR="16753920"  # Decimal for Orange
            IMAGE_TAGS="dev"
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            BRANCH="${GITHUB_REF#refs/tags/}"
            BRANCH_COLOR="2201331"   # Decimal for Blue
            IMAGE_TAGS="${BRANCH}, latest"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
            BRANCH_COLOR="10233776"  # Decimal for Purple
            IMAGE_TAGS="${{ env.DOCKER_TAGS }}"
          fi

          # Create a simpler JSON payload with less string manipulation in jq
          cat > discord-payload.json << EOF
          {
            "embeds": [{
              "title": "🚀 Docker Build Success: ${{ github.repository }}",
              "color": $BRANCH_COLOR,
              "description": "A new Docker image has been built and pushed to the container registry.",
              "fields": [
                {
                  "name": "🏷️ Version",
                  "value": "${{ env.RELEASE_VERSION }}",
                  "inline": true
                },
                {
                  "name": "🔖 Branch/Tag",
                  "value": "$BRANCH",
                  "inline": true
                },
                {
                  "name": "🧠 Commit",
                  "value": "[\`$SHORT_SHA\`]($COMMIT_URL)",
                  "inline": true
                },
                {
                  "name": "🏙️ Image",
                  "value": "ghcr.io/${{ github.repository }}",
                  "inline": false
                },
                {
                  "name": "📋 Tags",
                  "value": "$IMAGE_TAGS",
                  "inline": false
                }
              ],
              "thumbnail": {
                "url": "https://github.com/cyb3rgh05t/brands-logos/blob/master/StreamNet/icons/2.png?raw=true"
              },
              "footer": {
                "text": "Built with ❤️ by ${{ github.repository_owner }}",
                "icon_url": "https://github.com/${{ github.repository_owner }}.png"
              },
              "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            }]
          }
          EOF

          # Send the webhook if DISCORD_WEBHOOK is defined
          if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
              -H "Content-Type: application/json" \
              -d @discord-payload.json
          fi
